[package]
name = "test-utils"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
babylon-apis     = { path = "../apis" }
babylon-proto    = { path = "../proto" }
babylon-bitcoin  = { path = "../bitcoin" }
cargo_metadata   = { workspace = true }
cosmwasm-std     = { workspace = true }
hex              = { workspace = true }
k256             = { workspace = true }
prost            = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
