[package]
name = "ics23-commitment"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
anyhow         = { workspace = true }
ics23        = { workspace = true }
prost        = { workspace = true }
thiserror   = { workspace = true }
tendermint-proto = { workspace = true }
